plugins {
  id("software.sava.build.feature.hardening")
}

testModuleInfo {
  // the RPC-fetcher wiring tests stand up an in-JVM JSON-RPC capture server
  requires("jdk.httpserver")
  requires("org.junit.jupiter.api")
  runtimeOnly("org.junit.jupiter.engine")
}

hardening {
  mutation.register("spl") {
    // catch-all by exclusion, so a new hand-written class is mutated by default
    // instead of silently skipped — the whole module is account encode/decode
    // and instruction building, which is exactly the money-critical shape.
    // NAKED_RECEIVER makes dropped fluent calls (receiver-returning
    // expressions) expressible; BIG_INTEGER reaches the u64/u128
    // reinterpretation math in core.math.SafeMath, which is method calls that
    // MathMutator (primitive bytecode ops) cannot see — trial numbers in
    // config/pitest/README.md.
    mutators = "STRONGER,EXPERIMENTAL_BIG_INTEGER,EXPERIMENTAL_NAKED_RECEIVER"
    declineMutator(
      "EXPERIMENTAL_BIG_DECIMAL",
      "trialed 2026-07-25: generated 0 against 4 call sites. It rewrites only " +
          "(BigDecimal)BigDecimal arithmetic, and every BigDecimal operation here is a " +
          "divide(BigDecimal, MathContext) / divide(BigDecimal, int, RoundingMode) " +
          "overload in StakePoolState.calculateSolPrice and Fee.toRatio, which it does " +
          "not rewrite. Those four sites are covered instead by NAKED_RECEIVER (the " +
          "dropped stripTrailingZeros family) and by StakePoolStateTests' exact-value " +
          "assertions.",
    )
    targetClasses = listOf("software.sava.idl.clients.spl.*", "software.sava.idl.clients.core.*")
    excludedClasses = listOf(
      // generated per-program code: correctness belongs to idl-src-gen, and
      // mutating the boilerplate would bury the hand-written signal
      "software.sava.idl.clients.*.gen.*",
      // test and fuzz sources share the recompiled root
      "software.sava.idl.clients.spl.*Test*",
      "software.sava.idl.clients.spl.*Fuzz*",
      "software.sava.idl.clients.core.*Test*",
      // 'Integ.*' scratch files are git-ignored: present on a dev machine and
      // absent in CI, so mutating them would make the baseline machine-dependent
      "software.sava.idl.clients.*.Integ"
    )
    // The 59 this glob swallows are generated bindings across 15 gen packages plus
    // the shared generated commons in core.gen. The other globs swallow nothing —
    // the test/fuzz roots are subtracted as test sources, and this module has no
    // Integ.java at all, so declining that glob here would be reported as stale.
    declineExclusionAudit(
      "software.sava.idl.clients.*.gen.*",
      "idl-src-gen output: per-program instruction builders, account and type " +
          "(de)serialization, PDA helpers and error enums generated from each program's IDL, " +
          "with the idl.json they were generated from committed beside them in gen/. Every one " +
          "carries '@generated by sava-software idl-src-gen — DO NOT EDIT' and is never " +
          "hand-edited here (AGENTS.md: fixes belong in the generator, then regenerate), so a " +
          "ratchet on them would pin code this repo cannot change. This suite's 59 also include " +
          "the shared generated commons in software.sava.idl.clients.core.gen — SerDe, " +
          "SerDeUtil, RustEnum, Factory, ProgramError — which every program's generated code " +
          "compiles against: same generator, same ownership. Correctness is carried instead by " +
          "the generator's own tests; by tools/idl_probe.py and tools/ground_truth.py " +
          "(docs/PROGRAM_VERIFICATION.md); and by execution rather than mutation — six test " +
          "sources (SPLClientTests, StakeProgramTests, TokenProgramTests, " +
          "AddressLookupTableTests, SystemProgramTest, Token2022ProgramTests) build and decode " +
          "through the generated instruction builders and account types. The hand-written " +
          "layer stays mutated: core.math.SafeMath and the stake/stake-pool parsers are this " +
          "suite's own baseline rows, and the four fuzz harnesses target them, not gen.",
    )
    targetTests = "software.sava.idl.clients.*Test*"
  }
  fuzz.register("validatorList") {
    targetClass = "software.sava.idl.clients.spl.stakepool.ValidatorListFuzz"
    // header (9) plus a few dozen 73-byte validator entries reaches every parse
    // path; larger inputs only slow executions down. Seeded with the head of a
    // real mainnet list — every prefix is valid, so the corpus is here to hold
    // findings, not to bootstrap coverage
    maxLen = 4096
    seedCorpus = layout.projectDirectory.dir("src/test/resources/fuzz/validatorList")
  }
  fuzz.register("stakePoolState") {
    targetClass = "software.sava.idl.clients.spl.stakepool.StakePoolStateFuzz"
    // the packed account is ~600 bytes; a little headroom lets the mutator probe the
    // option-byte branches past a seed. Seeded with a real mainnet account
    maxLen = 1024
    seedCorpus = layout.projectDirectory.dir("src/test/resources/fuzz/stakePoolState")
  }
  fuzz.register("precompileOffsets") {
    targetClass = "software.sava.idl.clients.spl.precompiles.PrecompileOffsetsFuzz"
    // a u8 count (max 255) with 11/14-byte records: 2 + 255*14 ~= 3.5KB covers every
    // record; the whole space is reachable from scratch, so the corpus is a place
    // for findings to land rather than a bootstrap
    maxLen = 256
    seedCorpus = layout.projectDirectory.dir("src/test/resources/fuzz/precompileOffsets")
  }
  fuzz.register("stakeAccount") {
    targetClass = "software.sava.idl.clients.spl.stake.StakeAccountFuzz"
    // the account is a fixed 200-byte layout; headroom lets the mutator probe
    // over-long inputs. Seeded with a real mainnet stake account so the Stake
    // state's populated tail is reachable
    maxLen = 256
    seedCorpus = layout.projectDirectory.dir("src/test/resources/fuzz/stakeAccount")
  }
}
